### PR TITLE
[TS] LPS-133316 Avoid processing the same article multiple times during the same export process

### PR DESCRIPTION
**Pull request by balazssk**
Hi Vendel,

I've extended https://github.com/liferay/liferay-portal/commit/c8d031a9dde38f7c5ee0f97ec6a48b9a65612d90 from LayoutExportSucceeded and LayoutExportFailed to PortletExportSucceeded and PortletExportFailed

Can you please review?
https://issues.liferay.com/browse/LPS-133316

Thanks,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
