### PR TITLE
[TECHNICAL SUPPORT] LPS-125446 When Exporting Display style changes back to default in the Publishing section

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,
[LPS-125446](https://issues.liferay.com/browse/LPS-125446)

I implemented the same feature in export/import as in staging under [LPS-124969](https://issues.liferay.com/browse/LPS-124969).

Please review my changes,

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Hi @NemethNorbert ,

It seems like all of the failing tests have something like `Element is not present at "//ul/li/div/h2//a"`.
Also, these tests have ran successfully in the past, e.g.:
https://testray.liferay.com/home/-/testray/case_results/1392237221/history?tab=result&hideFilterPin=true

Is it possible that these failures are related to the code change?

Thanks,
Vendel

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by NemethNorbert** [comment]
Hey @vendeltoreki ,

I updated my solution and resolved the error. Thanks for the heads up, I think it looks good now

**Comment by vendeltoreki** [comment]
Thanks @NemethNorbert ,

I've checked the changes and it works as expected.

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
