### PR TITLE
[TS] LPS-127729

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
ci:test:relevant

**Comment by crodriguezy** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by crodriguezy** [comment]
Hi @vendeltoreki I had a quick look at the results of the tests and it seems to me they are not caused by these changes. Please correct me if I'm wrong.
Kind regards.

**Comment by vendeltoreki** [comment]
Hi @crodriguezy ,

Yes, they don't seem to be related.

However, I was wondering whether we have test cases for this. I remember for example https://github.com/liferay/liferay-portal/blob/master/modules/apps/export-import/export-import-test/src/testIntegration/resources/com/liferay/exportimport/internal/content/processor/test/dependencies/layout_references.txt
But it seems like it doesn't have any URLs containing /-/.

Can you please check whether there are any test cases that can be extended to cover this, with minimal modification?

Thanks,
Vendel

**Comment by crodriguezy** [comment]
Hi @vendeltoreki , yes I'll have a look.

Do you think though it is safe to provide the customer with an SDH including this fix? It's a bit urgent and I tested the case of /-/ still works.

Thank you again.

**Comment by vendeltoreki** [comment]
I think it's good to go as a hotfix. Export/import might also be affected, but that can be handled as a separate issue.

**Comment by crodriguezy** [comment]
Hi @vendeltoreki , could you please check if the tests I added are enough (and correctly placed) to test this case?
Thank you!

**Comment by crodriguezy** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
Hi @crodriguezy ,

Thanks for the test. I've ran it a few times and it only succeeds with your changes. I added one more commit and will forward from: https://github.com/vendeltoreki/liferay-portal/pull/172

**Comment by crodriguezy** [comment]
Thank you @vendeltoreki !

**Pull request closed without merging**
