### PR TITLE
Lps 107677 1

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @knchau

This fix requires https://github.com/brianchandotcom/liferay-portal/pull/84597 to be in branch before it can be tested.

Notes from Kim:
> https://issues.liferay.com/browse/LPS-107677
> **Issue:**
> When import a site, Additional information button is displayed even though there are no changes between the site template and the site.
> 
> **Solution:**
> Adding property configuration to allow the user to set parameter `PortletDataHandlerKeys.LAYOUT_SET_PROTOTYPE_LINK_ENABLED`.

### CODE REVIEW

**Comment by vendeltoreki** [comment]
Hi @knchau ,

I've checked your solution, but not in detail yet. As I see, you are adding a new checkbox that can turn off site template propagation right at the import phase, avoiding the "This page has been changed ..." message.

While this can also solve the problem, I see another place where it might be possible to get the same result without adding new options: in [InformationMessagesProductNavigationControlMenuEntry.isModifiedLayout(..)](https://github.com/liferay/liferay-portal/blob/e00cf5f88d339471e822fe070a2557ecfa78fb9c/modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/product/navigation/control/menu/InformationMessagesProductNavigationControlMenuEntry.java#L167)
My guess is that this call returns the wrong result: SitesUtil.isLayoutModifiedSinceLastMerge(layout).

I will continue testing tomorrow. I think the real problem is that we don't update `last-merge-time` or `modifiedDate` correctly at the import.

**Comment by knchau** [comment]
Hi @vendeltoreki,

Thanks for the thorough response! I did notice that `modifiedDate` would be frequently updated whereas `last-merge-time` does not get updated although I am not sure where it would be appropriate to update the `last-merge-time`.

[StagedLayoutSetStagedModelDataHandler.doImportStagedModel(..)](https://github.com/liferay/liferay-portal/blob/4d80f31fce068237f785b43bb13f4b0e09a6af1b/modules/apps/layout/layout-impl/src/main/java/com/liferay/layout/internal/exportimport/data/handler/StagedLayoutSetStagedModelDataHandler.java#L359) adds the layout as a modified layout (since it also calls [SitesUtil.isLayoutModifiedSinceLastMerge(..)](https://github.com/liferay/liferay-portal/blob/4d80f31fce068237f785b43bb13f4b0e09a6af1b/modules/apps/layout/layout-impl/src/main/java/com/liferay/layout/internal/exportimport/data/handler/StagedLayoutSetStagedModelDataHandler.java#L129)) and so `last-merge-time` would not be updated [here](https://github.com/liferay/liferay-portal/blob/4d80f31fce068237f785b43bb13f4b0e09a6af1b/modules/apps/layout/layout-impl/src/main/java/com/liferay/layout/internal/exportimport/data/handler/StagedLayoutSetStagedModelDataHandler.java#L371) too. 

Please let me know if you have any updates from your testings.

Thanks again!

**Comment by vendeltoreki** [comment]
Hi @knchau ,

You are correct, the `last-merge-time` is not updated. However, the root cause is that when we import the LayoutSetPrototype (the actual template), its Layout gets a `last-merge-time` property as well (the portal has only one way to import a template, which is the same as the propagation itself). The Layouts that belong to a Prototype should not have this property, as these are the ones that we actually merge from.
My change ( https://github.com/vendeltoreki/liferay-portal/commit/5c7013973cba10b39c80f9833886ba1bfd453db1 ) prevents the incorrect template import. However, in the scenario mentioned on [LPS-107677](https://issues.liferay.com/browse/LPS-107677), it only works correctly after the user clicks on Reset. I'm still checking if there's a solutino for that.

**Comment by knchau** [comment]
Hi @vendeltoreki,

Do you have any updates for the scenario mentioned on LPS-107677? If there is anything you'd like me to help with, please let me know :)

**Comment by vendeltoreki** [comment]
Hi @knchau ,

The change ( https://github.com/vendeltoreki/liferay-portal/commit/5c7013973cba10b39c80f9833886ba1bfd453db1 ) I was experimenting with almost solved the problem. The `Reset Changes` button works correctly, but as far as I know, it should not even appear in this scenario.
The reason why it appears is that at site import phase, the `last-merge-time` is read from the LAR. It refers to the time when the template propagation last happened, before the export. Unfortunately, the Layout import updates its `modifiedDate`, and from this point the Layout is treated as 'Modified'.
The `modifiedDate` is updated [here](https://github.com/liferay/liferay-portal/blob/6860484ed483834ee2256579f73de7da8ca4cddf/modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/exportimport/data/handler/LayoutStagedModelDataHandler.java#L760) and [here](https://github.com/liferay/liferay-portal/blob/496ab43c62ade6a10706269e559d4231d83d36ec/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/controller/PortletImportControllerImpl.java#L1372).

I thought it would be too complex to avoid updating `modifiedDate`. However, I realized that we can work around this by triggering a site template propagation right after the import. This will update the `last-merge-time` with a new value, and `modifiedDate` will be older.

I've sent a PR, so you can make sure this works for your case: https://github.com/knchau/liferay-portal/pull/15

Thanks,
Vendel

**Comment by knchau** [comment]
Hi @vendeltoreki,

Thank you for the thorough explanation, I really appreciate it! I have tested https://github.com/knchau/liferay-portal/pull/15 and it does resolve LPS-107677.

I can provide this solution to the customer. Thanks again!! :)

**Comment by vendeltoreki** [comment]
Hi @knchau , @SamZiemer ,

I've forwarded the modified fix: https://github.com/brianchandotcom/liferay-portal/pull/85459

Regards,
Vendel

**Pull request closed without merging**
