### PR TITLE
LPS-121695

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
ci:test:sf

**Comment by crodriguezy** [comment]
ci:test:relevant

**Comment by crodriguezy** [comment]
Hi @vendeltoreki , could you please take a look at this PR? There is a customer blocked by LPS-121695
Thank you!

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by crodriguezy** [comment]
HI @vendeltoreki , I think those failures are not directly related to this PR. I previously sent it to my user and as you can see no tests were broken: https://github.com/crodriguezy/liferay-portal/pull/186

**Comment by vendeltoreki** [comment]
Hi @crodriguezy ,

Yes, the test failures seem irrelevant. However, is it possible to create a new test case for this change?

Thanks,
Vendel

**Comment by crodriguezy** [comment]
Ok, I will create a specific test, but I would like to provide the customer with a fix for this asap, they are in a hurry.
Do you consider this change safe to be delivered?
Thank you

**Comment by vendeltoreki** [comment]
I did not have time to test it completely. But if it fixes LPS-121695 and the case for LPS-91735 and LPS-88197 doesn't fail, I think it's good to go as a hotfix.

**Comment by vendeltoreki** [comment]
Forwarded to: https://github.com/liferay-forms/liferay-portal/pull/17

**Comment by crodriguezy** [comment]
Hi @vendeltoreki , I've seen this PR has finally been forwarded to Brian. Thanks for reviewing it.

Do you still consider a test would be necessary? I've been having some trouble developing it, but I could send you one of the versions if you require it.

**Comment by vendeltoreki** [comment]
Hi @crodriguezy ,

Since it was mostly code deletion to align the functionality with the other StagedModelDataHandlers, I don't think testing is necessary in this case. It's unlikely that any change would break this new test case again.

**Comment by crodriguezy** [comment]
Ok @vendeltoreki !

Regards

**Pull request closed without merging**
