### PR TITLE
[TS] LPS-122262

### PR DESCRIPTION
**Pull request by bakayattila**
Hi @vendeltoreki,

Could you review this?

https://issues.liferay.com/browse/LPS-122262
Best,
Attila

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
