### PR TITLE
LPS-134442

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by marianoalvarosaiz** [comment]
Hi @vendeltoreki,
 do you have any updates about this PR?
Kind regards.

**Comment by vendeltoreki** [comment]
Hi @marianoalvarosaiz ,
Sorry for the delay. I've reviewed the code and added some test cases. Forwarding through https://github.com/brianchandotcom/liferay-portal/pull/103752 .

**Comment by marianoalvarosaiz** [comment]
No worries. Thanks a lot @vendeltoreki!

**Pull request closed without merging**
