### PR TITLE
[TS] LPS-116620 Split up changesetEntryIds when using SQL Server

### PR DESCRIPTION
**Pull request by balazssk**
Hi @vendeltoreki ,

This proposed fix limits ChangesetEntry deletions to 2000 at a time if the used DB is SQL Server. 
The issue comes from an SQL Server limitation. Queries can only have 2100 parameters. During my tests, I could only add 2098 parameters for a dynamicQuery's IN criteria (maybe the table name and the * are also counted). I've chosen 2000 as a limit without any specific reason. 

Can you please review?
https://issues.liferay.com/browse/LPS-116620

Thanks,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
I checked the errors, they seem to be unrelated to this change:
```LocalFile.StagingUsecase#PublishWebContentWithFeeds
LocalFile.Staging#StagingRemoteWithDynamicExportLimit
LocalFile.Staging#PublishChildSiteViaRemoteStagingWithParentStructure
LocalFile.Staging#StagingRemoteLiveWebContentWithManualChosenID
LocalFile.ExportImport#ExportImportPortletWithADT
LocalFile.SitetemplatesUsecase#AddPageTemplatesWithDuplicateNameViaSiteTemplate
LocalFile.Staging#CreateWidgetTemplateWhenNotStagedADT
```

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
