### PR TITLE
LPS-140009 When displayStyleGroupId is not present in portletPreferences but displayStyle is present, export could fail with NoSuchGroupException

### PR DESCRIPTION
**Pull request by jgarcialr**

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by jgarcialr** [comment]
Hi @vendeltoreki ,
It seems the failed test is failing also to other pr's.

Should I rewiev something about this PR and resend or is ok?

**Comment by vendeltoreki** [comment]
Hi @jgarcialr ,

Yes, `LocalFile.RemoteStaging#StagingRemoteLiveWebContent` seems to be failing on others too.
I'm just running a few manual tests locally and forward the request.

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
