### PR TITLE
[TECHNICAL SUPPORT] LPS-124969 Display style is not preserved in publishing/staging

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey @vendeltoreki,
[LPS-124969](https://issues.liferay.com/browse/LPS-124969)

I implemented the solution that has been suggested in [LPS-111067](https://issues.liferay.com/browse/LPS-111067?focusedCommentId=2333577&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2333577)

please review it.

Thanks,

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
Hi @NemethNorbert ,

The changes look ok, staging test failures seem to be caused by other changes.

I'm forwarding your PR.

Thanks,
Vendel

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
