### PR TITLE
LPS-113739 Semantic Versioning.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by marianoalvarosaiz** [comment]
Rebased here https://github.com/vendeltoreki/liferay-portal/pull/61

**Pull request closed without merging**
