### PR TITLE
LPS-136726 Avoid error exporting Expandos when there are missing ClassName entries

### PR DESCRIPTION
**Pull request by joseluisbango**
Hello @vendeltoreki,

If there is any inconsistency in Expando tables related to ClassName entries (due to a problematic upgrade, for example), it is not possible to export valid Custom Fields (an error occurs). 

The code should be robust enough to allow a successful export despite these inconsistencies.

If you have any doubt, please let me know.

Regards,

Jose

### CODE REVIEW

**Comment by joseluisbango** [comment]
ci:test:sf

**Comment by joseluisbango** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by joseluisbango** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Closing PR: forwarding through https://github.com/vendeltoreki/liferay-portal/pull/222

**Pull request closed without merging**
