### PR TITLE
[TS] LPS-130397 Attempt to get the file entry based on the file name as well as title

### PR DESCRIPTION
**Pull request by jonathanmccann**
If a file named "test.png" is added to the Document Library then the file can be accessed by either of the following URLs:

http://localhost:8080/documents/41371/0/test.png
http://localhost:8080/documents/41371/0/test

This is due to the file entry having a _fileName_ as well as a _title_. In https://issues.liferay.com/browse/LPS-123544 the logic was updated to account for both possibilities - https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/webserver/WebServerServlet.java#L457-L469

The changes in this pull are the same allowing for getting the file based on either field.

The difference in testing on https://issues.liferay.com/browse/LPS-130397 could be attributed different URLs being used thus causing the discrepancy with QA's testing.

Please let me know if there are any questions or issues. Thank you.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
Checked the test failures:
* `LocalFile.ExportImport#ExportImportLayoutCircularReference` is not unique, was caused by [LPS-133752](https://issues.liferay.com/browse/LPS-133752)
* `LocalFile.RemoteStaging#StagingRemoteLiveWebContent` doesn't seem to be a real issue, more like a test timing problem

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
