### PR TITLE
[TS] LPS-121342

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Hi @vendeltoreki @moltam89

Same changes than https://github.com/vendeltoreki/liferay-portal/pull/124 PR, but I have replaced the commit that changed TunnelUtil classloader with this one [`547b024` (#126)](https://github.com/vendeltoreki/liferay-portal/pull/126/commits/547b0249dd515979a05e00ca740cf7d66ce6c44e) that changes the thread classloader to `PortalClassLoaderUtil.getClassLoader()` before calling TunnelUtil, because the thread classloader is the one used during response deserialization.

I have agreed this alternative solution with @csierra

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
Hi @jorgediaz-lr ,

According to Brian's comment ( https://github.com/brianchandotcom/liferay-portal/pull/94598#issuecomment-700168031 ), we will need tests for every new scenario.

Can you please add a new test for this?

Remote staging is a bit more complicated to test. However, I've found some examples: https://github.com/liferay/liferay-portal/search?l=Java&q=test+enableRemoteStaging .

Thanks,
Vendel

**Comment by jorgediaz-lr** [comment]
Hi @vendeltoreki 

Do you want to add new tests to test the new hasRemoteLayout and getRemoteLayout methods in StagingImplTest, or is it necessary to test anything else?

I saw that StagingGroupHelperTest is also testing some remote staging stuff, so I will base my new tests in both StagingGroupHelperTest and DDMFormStagingTestUtil classes

Regards,
Jorge

**Comment by vendeltoreki** [comment]
Hi @jorgediaz-lr ,

Yes, I think it's enough to test the new service methods. As I see, they contain most of the logic.

Thanks,
Vendel

**Comment by jorgediaz-lr** [comment]
New PR with tests sent here https://github.com/vendeltoreki/liferay-portal/pull/127

**Pull request closed without merging**
