### PR TITLE
LPS-123156 As a Content Publisher, I want to have clear distinction among Staging and Publications UI labels and phrases

### PR DESCRIPTION
**Pull request by moltam89**

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test:sf

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
ci:test:sf

**Comment by moltam89** [comment]
ci:test:sf

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
Functional tests failures:
1. LocalFile.WebContentWithPermissions#AddAndViewStructureAndTemplateWithPermissions has been fixed under [LRQA-63043](https://issues.liferay.com/browse/LRQA-63043).
2. ContentPagesWithMapping#ViewMappableFieldsAreGroupedByFieldset will be fixed under LRQA-63190.
3. WebContentDisplayWithStaging#StagingPublishWCWithImageFieldEdit will be fixed under LRQA-63188.
4. WebContentExportImport#MoveImportedWebContentArticlesToFolders will be fixed under LRQA-63188.
5. StagingUsecaseWithVersioning#StagingPublishLast is related to the current commit, I'll fix this test after the new changes merge into portal.

**Comment by JoyceWang08211** [comment]
Do a test-fx for StagingUsecaseWithVersioning#StagingPublishLast under https://issues.liferay.com/browse/LRQA-63209.

**Comment by JoyceWang08211** [comment]
Pushed the test-fix to @moltam89 and quarantine two failed tests for forwarding this PR.
https://github.com/moltam89/liferay-portal/pull/560

**Comment by moltam89** [comment]
Rebased and added the test related changes at https://github.com/vendeltoreki/liferay-portal/pull/149.

**Pull request closed without merging**
