### PR TITLE
[TS] LPS-138734 NoSuchLayoutSetBranchException error when using Publish Templates after disabling/enabling page versioning

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-138734

The error is produced in case a customer creates a Publish Templates and it disables and re-enables page versioning or disconnect and reconnect Remote staging.

The customer that has reported this issue is using Remote Staging with page versioning enabled and in case they detect an issue in the Life side they sometimes disconnect the remote staging to check the portlets configuration (this configuration cannot be accessed when remote staging is enabled)

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:stop

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
Hi @jorgediaz-lr ,

The changes look ok to me. However, the staging CI test is stuck for some reason. I'm trying to run it on a separate pull now to see if it causes any failures: https://github.com/vendeltoreki/liferay-portal/pull/226

Regards,
Vendel

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
