### PR TITLE
[TS] LPS-99297

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-99297

Same pull than https://github.com/brianchandotcom/liferay-portal/pull/86844 but I have added:

 1. Commit https://github.com/vendeltoreki/liferay-portal/pull/66/commits/5e03f383d727fc9eb4bcf2040e6cd0ad4997c8b2 with the changes requested by Brian in this comment https://github.com/brianchandotcom/liferay-portal/pull/86844#issuecomment-604724908
 2. Commit https://github.com/vendeltoreki/liferay-portal/pull/68/commits/4a8db649a7a3bd34c35678b4ac5edb5863e6593b with the changes to fix the integration tests that are failing, see: https://github.com/vendeltoreki/liferay-portal/pull/66#issuecomment-641481829

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
