### PR TITLE
LPS-136324

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-136324

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
ci:test:staging

**Comment by moltam89** [comment]
Hi @mbowerman ,

The failing tests seem to be related to the fix, could you please check them?

Thanks,
Tamas

**Comment by mbowerman** [comment]
Thanks for the feedback @moltam89 ! I looked at the test failure and it seems to be testing for what I believe is a rare case - when the servlet mapping can be parsed as a real locale. It might be somewhat complicated to solve for this case, so I may take a few days before I can fix this test failure.

**Comment by mbowerman** [comment]
Closing this for now, I'll need more time to work on this

**Pull request closed without merging**
