### PR TITLE
LPS-136726 Avoid error exporting Expandos when there are missing ClassName entries

### PR DESCRIPTION
**Pull request by vendeltoreki**
Forwarding from https://github.com/vendeltoreki/liferay-portal/pull/221
cc: @joseluisbango

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
ci:forward

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
