### PR TITLE
LPS-133316 Don't use cache from previous export

### PR DESCRIPTION
**Pull request by balazssk**
Hi @vendeltoreki ,

Previous solution of dropping the cache after portlet export invalidated the use of the cache. While https://issues.liferay.com/browse/LPS-131585 is being investigated, this should be a fair way to reset the cache when needed.

Can you please review?
https://issues.liferay.com/browse/LPS-133316

Thanks,
Balázs

p.s.
related to https://issues.liferay.com/browse/LPS-131585

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
**Notes:** This fix basically works around the cache invalidation problem; only uses the cache when this content hadn't been processed yet during the current export process. Works for both use cases: [LPS-133316](https://issues.liferay.com/browse/LPS-133316) and [LPS-131585](https://issues.liferay.com/browse/LPS-131585).

Checked failing CI tests:
* `LocalFile.RemoteStaging#StagingRemoteLiveWebContent`: not unique, already failed with the same error in [testray](https://testray.liferay.com/home/-/testray/case_results/1541893046/history?tab=result&hideFilterPin=true)
* `LocalFile.Staging#ViewLastPublishDateBehaviourAfterInitialPublication`: same error: `java.net.ConnectException: Failed to connect to localhost`
* `LocalFile.StagingUsecase#ViewSingleAssetPublication`: same error: `java.net.ConnectException: Failed to connect to localhost`

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
