### PR TITLE
[TS] LPS-133999

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @mbowerman

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
Hi @moltam89 ,

Can you please help me reviewing this pull request?

Thanks,
Vendel

**Comment by moltam89** [comment]
Hi  @mbowerman ,

I'm not sure if the checkDefaultLayoutSetBranches call is really necessary. Is there a use case where the master layout set branch is not created yet? Please note that in case of remote staging, the stagingGroup.getLiveGroup() will return null.

Also, I think the new logic will fail if the layout already exists, as the master layout branch exists as well in that case.

Best,
Tamas

**Comment by mbowerman** [comment]
Hi @moltam89,

> I'm not sure if the checkDefaultLayoutSetBranches call is really necessary. Is there a use case where the master layout set branch is not created yet?

My bad, you are right. I thought I had encountered a case in my testing where the master layout set branch wasn't created yet, but I can no longer seem to reproduce it.

I've removed the `checkDefaultLayoutSetBranches` call along with the `StagingLocalService` declaration from the commit.

> Please note that in case of remote staging, the stagingGroup.getLiveGroup() will return null.

Acknowledged, thanks for the heads up. Fortunately, it looks like we no longer need the live group, now that we have removed the `checkDefaultLayoutSetBranches` call.

> Also, I think the new logic will fail if the layout already exists, as the master layout branch exists as well in that case.
You are right. I changed the `addLayoutBranch` call to `getMasterLayoutBranch`, as this method will automatically add the master layout branch in the case that it doesn't exist yet.

I've updated the commit in my pull request, please take another look when you get another chance.

I also have a question: should I include the line that automatically updates the status to APPROVED? If I don't include this line, then the user would have to go to all the non-(Link to URL/Link to Layout) pages they imported and explicitly toggle the "Ready for Publish Process" slider for those pages. I believe for Link to URL/Link to Layout pages, the status should get set to APPROVED automatically when calling `addLayoutRevision` (see [here](https://github.com/liferay/liferay-portal/blob/45ae9fdb3289da4ded5bd9f575b3389710871a72/portal-impl/src/com/liferay/portal/service/impl/LayoutRevisionLocalServiceImpl.java#L138)).

**Comment by moltam89** [comment]
Hi @mbowerman ,

I tend to think that we shouldn't set revisions APPROVED automatically, users could decide later whether they want to publish the revisions to Live, or not.

I'm still investigating this fix, mostly the part when the layout already exists concerns me. This is a slightly different use case.
If I'm not very much mistaken, if the layout already exists, the latest layout revision will be used during the update, which can belong to another layout set branch/layout branch.

The current fix seems good to me, but I'd like to make sure that it will fit into the bigger picture.
I'll get back to you soon.

Thanks,
Tamas

**Comment by moltam89** [comment]
Hi @mbowerman ,

Here is my solution which handles the case when the layout already exists:
https://github.com/moltam89/liferay-portal/pull/620

I'm planning to forward this to Brian, if it's fine with you and passes the tests.

Best,
Tamas

**Comment by vendeltoreki** [comment]
Closing PR as the code had been merged to master already

**Pull request closed without merging**
