### PR TITLE
LPS-121138 As a Site Template Administrator, I want to have the site template propagation run parallel to multiple sites

### PR DESCRIPTION
**Pull request by moltam89**

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
Closing, forwarded to: https://github.com/vendeltoreki/liferay-portal/pull/151

**Pull request closed without merging**
