### PR TITLE
LPS-113197 Fetch missing DDL Record

### PR DESCRIPTION
**Pull request by jonathanmccann**
This handles an issue when adding a record to a DDL within a DDL widget and then attempting to publish. It is the same change as done earlier for this ticket for DDL Record Set.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
This PR isn't relevant anymore, since the changes were resent to https://github.com/vendeltoreki/liferay-portal/pull/73 and merged into master.  Please close this PR.

**Comment by jonathanmccann** [comment]
ci:close

**Pull request closed without merging**
