### PR TITLE
[TS] LPS-120962

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Hi @jonathanmccann ,

The changes look ok, but the CI keeps failing for some reason. I'll give it another try and forward it manually on Monday if it's still not working.

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Forwarded through https://github.com/vendeltoreki/liferay-portal/pull/123 and https://github.com/brianchandotcom/liferay-portal/pull/94543

**Pull request closed without merging**
