### PR TITLE
LPS-120490

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-120490

/cc @haubuicodeengine

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
It's consistently failing and marking it as a unique failure, but I don't really see how a change to staging that doesn't modify any non-internal classes can prevent starting up a Tomcat bundle.

I'm guessing it's related to the module not having been tested in awhile, so I'll send a pull request with a dummy change to verify.

**Comment by vendeltoreki** [comment]
Thanks, @holatuwol . I will review the code changes and run the tests later. I've seen this error on other pulls as well.

**Comment by vendeltoreki** [comment]
Hi @haubuicodeengine , @holatuwol ,

The code changes look ok. I will forward it as soon as the unrelated CI test failures got fixed.

Thanks,
Vendel

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
