### PR TITLE
LPS-116620 Simplify and fix 'in' clause overflow for oracle and sql server

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
Please see https://github.com/vendeltoreki/liferay-portal/pull/82

**Comment by Preston-Crary** [comment]
Please see https://github.com/vendeltoreki/liferay-portal/pull/84

**Pull request closed without merging**
