### PR TITLE
LPS-110358 Can't open failed publication's summary

### PR DESCRIPTION
**Pull request by rgusztus**
Hi @vendeltoreki,

Sending this PR in regards of LPS-110358. This commit does the job, however I beleive it would be better if we could set the summaryMenu variable to false for failed publications, but I couldn't find it where.

Anyhow, please check and let me know.
Thanks!

Best Regards,
Robert

### CODE REVIEW

**Comment by vendeltoreki** [comment]
Hi @rgusztus ,

Yes, I think you are right. Can you please check whether setting it in https://github.com/liferay/liferay-portal/blob/master/modules/apps/staging/staging-taglib/src/main/resources/META-INF/resources/process_list/page.jsp#L167 does have the same effect?

Thanks,
Vendel

**Comment by rgusztus** [comment]
Hi @vendeltoreki,

Indeed, it's much better in process list/page.jsp (yes, has the same effect)!
Please check & let me know ;)

Thanks!
Robi

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Thanks @rgusztus ,

I will check it out :)

**Comment by vendeltoreki** [comment]
CI error seems irrelevant, forwarded to https://github.com/brianchandotcom/liferay-portal/pull/86541

**Pull request closed without merging**
