### PR TITLE
[TEST] LPS-99330

### PR DESCRIPTION
**Pull request by vendeltoreki**

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test

**Comment by holatuwol** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
Hi @holatuwol ,

The ci:test:staging does not run here for some reason. I've ran all `LayoutSetPrototypePropagationTest` tests locally (including `testLayoutPropagationWithFriendlyURLConflict()`) and all passed.

**Comment by holatuwol** [comment]
Got it, I'll go ahead and forward the pull request. Thanks for the confirmation!

**Pull request closed without merging**
