### PR TITLE
[TS] LPS-128305

### PR DESCRIPTION
**Pull request by jonathanmccann**
From @brianikim:

>The issue occurs because the content string endPos is not properly ending on the backslash and is instead ending on a quote: https://github.com/liferay/liferay-portal/blob/bf41ac8d3aa2dbf64656fa7c0635882079d28f09/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/exportimport/content/processor/DLReferencesExportImportContentProcessor.java#L138

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by brianikim** [comment]
Hello @vendeltoreki ,

Let me know what you think about the fix. Also, let me know if the test result failure is due to the fix.

Sincerely,
Brian Kim

**Comment by vendeltoreki** [comment]
Hi @brianikim ,

I've added one test case, forwarding through https://github.com/vendeltoreki/liferay-portal/pull/179 .

**Pull request closed without merging**
