### PR TITLE
[TS] LPS-127517 Page getting deleted after disabling Remote Live Staging

### PR DESCRIPTION
**Pull request by bakayattila**
Hi @vendeltoreki,

Could you review this?
The issue is related to the modification on [LPS-119920](https://issues.liferay.com/browse/LPS-119920). To Prevent this use case I created a checker for the main variant.

https://issues.liferay.com/browse/LPS-127517

Thanks!
Attila

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
