### PR TITLE
LPS-131308 LoggerExportImportLifecycleListener should always log failures

### PR DESCRIPTION
**Pull request by dnebing**
Addresses ticket https://issues.liferay.com/browse/LPS-131308

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Hi @dnebing ,

I've checked those CI errors and they seem strange.. it's possible that these test cases (e.g.: DefaultExportImportContentProcessorTest.testImportLinksToLayoutsIdsReplacement) were failing even before, but your change made a different error message pop up earlier, and that's why CI does not see it as a unique failure. At least, that's my theory. 

Can you check those errors as well?

Thanks,
Vendel

**Comment by dnebing** [comment]
Either that or the original tests have been failing but, because the logger was not logging failures, the tests were falsely reporting success when they should have been failing.

I don't know enough about the tests to know which statement might be correct...

**Comment by dnebing** [comment]
Do we know who owns those tests? They might be the best folks to review the errors...

**Comment by vendeltoreki** [comment]
I will run these tests locally to see if there's an easy way to fix them. It seems like they already ignored those errors for some reason.

**Comment by vendeltoreki** [comment]
I could not find out why these tests are failing. When I run it locally, the methods you changed are not even invoked. However, when the change is there, we get a strange NPE and the error is printed. I will continue investigating.

**Comment by moltam89** [comment]
Resent the same fix here to see if the CI errors are still there:
https://github.com/moltam89/liferay-portal/pull/637

**Comment by vendeltoreki** [comment]
Closing PR, code merged to master already

**Pull request closed without merging**
