### PR TITLE
[TS] LPS-130051

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-130051

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
Passing SF test: https://github.com/liferay-echo/liferay-portal/pull/4162#issuecomment-812922060
Passing relevant tests: https://github.com/liferay-echo/liferay-portal/pull/4162#issuecomment-812930734

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
