### PR TITLE
[TS] LPS-132134

### PR DESCRIPTION
**Pull request by wanderlast**
https://issues.liferay.com/browse/LPS-132134
https://issues.liferay.com/browse/LPP-40819

Hi @vendeltoreki!

This is a fix related to site templates and the layoutUpdateable setting. When a site is created based off of a site template, the setting for whether layouts are allowed to be edited or not is passed down to the individual layouts of that site. However, when the setting is changed on the site template, the setting remains on widget page layouts and therefore a layout on a site can remain unable to be edited based off of the previous setting of the site template. This fix checks if a change was made to the setting, checks each layout on the site template to see if the setting is attached to that layout and then alters it on both the source layout as well as all layouts that have it as a source layout. Please let me know if you have any questions or concerns. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
Hi @wanderlast ,

Thanks for submitting these changes. I've started reviewing and the first thing I noticed is that the code doesn't actually update any Layout records, as there are no update calls in https://github.com/vendeltoreki/liferay-portal/pull/213/commits/8661135f73fdd3480b015dbbce7379e705d09912#diff-490e6b623fa128847123c6a1c0e92a878fbea64cb2b9e4ead82fff7825bcffe1R263 .
Also, it's possible that we don't actually have to update these values, we just have to define better conditions on whether or not a specific page is editable on a site.
There are multiple settings that complicate the scenario a little bit:
* You can set the `layoutsUpdateable` on the LayoutSetPrototype (in Configuration --> Site Template Settings)
* but also `layoutUpdateable` one-by-one on the pages (in page configuration on the template)

My guess is that we should keep these settings more-or-less separated:
* You can use the "_Allow site administrators to modify pages associated with this site template, even when propagation of changes is enabled._" setting to disable all page modifications in the sites created from this template. In this case the individual page settings can't override this decision (the checkboxes are actually disabled).
* When the Site Template level setting is enabled, you can still disable modification of individual pages. These are propagated through the `typeSettings` column to the target Layouts. Although, I'm not sure if this is correct, since the decision of whether or not a user can edit a page should be based on both Site Template and Page level settings. And both are stored in the template and not on the page itself.

I will investigate a little bit more to find out what can be the best solution.

Regards,
Vendel

**Comment by vendeltoreki** [comment]
Closing PR, see [comment](https://issues.liferay.com/browse/LPS-132134?focusedCommentId=2488730&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2488730) on [LPS-132134](https://issues.liferay.com/browse/LPS-132134).

**Pull request closed without merging**
