### PR TITLE
LPS-135975

### PR DESCRIPTION
**Pull request by mbowerman**
Process DL references in pages' Javascript

https://issues.liferay.com/browse/LPS-135975

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
Hi @mbowerman , 

The changes look ok. However, I think we should hold this back until 7.4 release is stabilized ([slack post](https://liferay.slack.com/archives/C03BTCQBQ/p1625604459060400)). If it's urgent for the customer, you can create an SDH from it.

Meanwhile, @gaborlovasdotcom , can you please help to find out why we get
`javascript error: Failed to execute 'elementsFromPoint' on 'Document': The provided double value is non-finite.`
errors in these tests:
* `LocalFile.ExportImport#EditExportTemplate`
* `LocalFile.Staging#StagingWithPublishTemplate`
* `LocalFile.StagingUsecase#EditPublishTemplate`

Thanks,
Vendel

**Comment by JoyceWang08211** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
ci:stop

**Comment by JoyceWang08211** [comment]
Hi @vendeltoreki,
It seems like the above issues only occurs on the current PR. These issues cannot reproduce on upstream. I'll investigate these and send you the test-fix under https://issues.liferay.com/browse/LPS-136196

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
Resend here with the test-fix:
https://github.com/vendeltoreki/liferay-portal/pull/216

**Comment by JoyceWang08211** [comment]
Resend here with the test-fix:
https://github.com/vendeltoreki/liferay-portal/pull/216

**Comment by vendeltoreki** [comment]
Closing PR, since changes were forwarded on https://github.com/vendeltoreki/liferay-portal/pull/216 .

**Pull request closed without merging**
