### PR TITLE
[TEST] LPS-143860 hibernate flush

### PR DESCRIPTION
**Pull request by vendeltoreki**

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
For the above unique functional failures:
1. LocalFile.ExportImport#EditExportTemplate is fixed under LPS-144615.
2. LocalFile.StagingUpgrade#TemplatePropagationShouldWorkAfterUpgrade701016 will be fixed under LPS-144427.

cc @vendeltoreki and @gaborlovasdotcom

**Comment by gaborlovasdotcom** [comment]
@vendeltoreki Are we still need this item to merged in?

**Comment by gaborlovasdotcom** [comment]
As discussed with the team, this change needs additional rework.
See [LPS-143860](https://issues.liferay.com/browse/LPS-143860) for further updates

**Comment by gaborlovasdotcom** [comment]
ci:close

**Pull request closed without merging**
