### PR TITLE
[TS] LPS-128159 export-import-web: Use request parameter if available

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi @vendeltoreki ,

**Ticket:** https://issues.liferay.com/browse/LPS-128159
**Previous PR:** https://github.com/vendeltoreki/liferay-portal/pull/173

In the previous PR, we encountered a breaking POSHI test, which helped reveal another pre-existing bug.

This PR accounts for both: 
- The bug in [LPS-128159](https://issues.liferay.com/browse/LPS-128159)
- The pre-existing bug, discovered by the POSHI test failure

For additional details, I have left detailed notes in the LPS under a comment: [#comment-2379855](https://issues.liferay.com/browse/LPS-128159#comment-2379855)

Feel free to let me know if you have any questions or would like me to change anything.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
