### PR TITLE
LPS-115692 SF

### PR DESCRIPTION
**Pull request by achaparro**
Hey @vendeltoreki,

Thank you for your collaboration in [PTR-1766](https://issues.liferay.com/browse/PTR-1766). Please, can you review the pull to solve the first of the issues for the option 1 mentioned there.

Thanks.

cc/ @Samziemer

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:forward

**Comment by achaparro** [comment]
Hi @vendeltoreki,

The failures are in common with upstream and we can manually forward it:
https://liferay.slack.com/archives/C19PWQ74J/p1592844187066300

Since you already forwarded then, can you do it manually? Do you want me to do it?

Thanks!

**Comment by vendeltoreki** [comment]
Hi @achaparro ,

Yes, the changes are ok. Can you please forward it?

Thanks,
Vendel

**Pull request closed without merging**
