### PR TITLE
LPS-140329

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-140329

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
I am not sure why the SF test is failing. I tried running `gradlew formatSource` on the staging-configuration-web module, but it doesn't make any changes or indicate any problems.

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:staging

**Pull request closed without merging**
