### PR TITLE
LPS-109854

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by yxingwu** [comment]
Hi @vendeltoreki ,
Hope you are the right person to review it.

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Hi @yxingwu ,

Yes, I'm reviewing the staging related changes. The https://github.com/vendeltoreki/liferay-portal/pull/48/commits/866f37bfa329b5fe9ebca9ad4103b776bba7b992 commit looks ok to me.

Thanks,
Vendel

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
