### PR TITLE
[TS] LPS-106146

### PR DESCRIPTION
**Pull request by ChrisKian**
Resent from https://github.com/vendeltoreki/liferay-portal/pull/21 rebased with SF errors (hopefully) resolved.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
Thanks, @ChrisKian .
Forwarded to: https://github.com/brianchandotcom/liferay-portal/pull/83933

I removed this change: https://github.com/vendeltoreki/liferay-portal/pull/22/commits/3bc9d73940b7bf919a85ddbdf1c5e8e5997fe81a
It seems like this exception name SF rule does not apply to JSPs.

**Pull request closed without merging**
