### PR TITLE
LPS-110701

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hello,

I believe you are now the Staging related reviewer but please let me know if that is not the case.

https://github.com/vendeltoreki/liferay-portal/commit/05d0c7c62ecfe6ef5bc48886d8717abe35f8a180 - This resolves the issue outlined on LPS-110701.

https://github.com/vendeltoreki/liferay-portal/commit/d859c6e05ff7a69432f34887eda48b583b881347 - This is necessary due to LPS-107012. That fix will always export references even if they are not modified and configured to only be exported if modified. I tested the steps for LPS-107012 after my changes and that issue is still fixed.

Please let me know if you have any questions or if you believe a different approach would be better.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Hi @jonathanmccann ,

Yes, I will review the changes.

Thanks,
Vendel

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
