### PR TITLE
LPS-128305

### PR DESCRIPTION
**Pull request by brianikim**
Hello @vendeltoreki ,

Additional commit for LPS-128305. Added backslash to legacy stop string patterns as well.

https://issues.liferay.com/browse/LPS-128305

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
Closing pull request, based on [LPS-128305 comment](https://issues.liferay.com/browse/LPS-128305?focusedCommentId=2385984&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2385984)

**Comment by vendeltoreki** [comment]
Closing PR, as ticket already closed

**Pull request closed without merging**
