### PR TITLE
LPS-121139 Only import the layout if the prototype changed

### PR DESCRIPTION
**Pull request by moltam89**

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test:sf

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by moltam89** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
Checked the failed tests:
```
LocalFile.ExportImport#ExportWebContentWithDeletedReference
LocalFile.ExportImport#ExportDMWithDeletedDocumentLink
LocalFile.ExportImport#ExportImportSiteWithReferencedWebContent
LocalFile.PGStaging#PublishWCIncludingTextsAndImages
LocalFile.StagingUsecase#ImportLARsOnStagedSite
LocalFile.Staging#PublishVocabularyDeletionViaRemoteStagingOnGlobalSite
```
These are not caused by this pull since they were failing in the [previous run](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1370390874) as well.

**Comment by vendeltoreki** [comment]
ci:forward

**Comment by vendeltoreki** [comment]
ci:forward

**Comment by vendeltoreki** [comment]
Reopening, so we can run CI tests on the pull.
cc: @gaborlovasdotcom

**Comment by gaborlovasdotcom** [comment]
ci:test:bundle

**Pull request closed without merging**
