### PR TITLE
LPS-133676 Integration Test

### PR DESCRIPTION
**Pull request by mbowerman**
Integration test for https://issues.liferay.com/browse/LPS-133676

Note: For some reason, there seems to be a strange behavior (a bug?) within the DLReferencesExportImportContentProcessor, which causes an extra "t" param to be appended to the imported URL. Therefore, I've removed the "t" param from the URL's before comparing them in this test.

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
