### PR TITLE
[TS] LPS-121342

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Hi @vendeltoreki 

We have a customer that is using Remote Staging that is complaining about the lack of information about which revision page is published in Live server

That problem was adressed for Local Staging in https://issues.liferay.com/browse/LPS-119922

I have extended that solution to also address the remote staging case:

- ([1st commit](https://github.com/vendeltoreki/liferay-portal/pull/124/commits/75be6edc27541106099419bc6af73349327651b7)) I have modified `_getLastImportLayoutRevisionId` method in init.jsp to get the layout page from remote server calling a new `StagingImpl.getRemoteLayout` method that is similar to existing `StagingImpl.getRemoteLayoutPlid`
- ([2nd commit](https://github.com/vendeltoreki/liferay-portal/pull/124/commits/42372ff7770241848cf14c9373609d6d9c905f34)) I have modified `StagingImpl.updateLastImportSettings` to update the last-import-layout-revision-id information when we are importing in Remote Staging
- ([3rd commit](https://github.com/vendeltoreki/liferay-portal/pull/124/commits/1258a4b4f3b61f3b7bb1e364e278bb649075291f)) I have done a small change in TunnelUtil.java to avoid a ClassNotFoundException
- (4th to 6th commits) I have done some improvements to minimize the numbers of calls to the remote server and to avoid some exceptions in case the Layout doesn't exist in Live.

Let me know if you need more information.

Regads,
Jorge

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:staging

**Comment by jorgediaz-lr** [comment]
ci:test:staging

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Rebased to latest master to avoid a conflict in portal-kernel/bnd.bnd

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
The staging errors seem to be related to test infrastructure, all their job history was mostly success in the past:
* LocalFile.PGStaging#PublishWCWithPagesVariationViaRemoteStaging
`org.openqa.selenium.NoSuchSessionException: no such session`
* LocalFile.Staging#StagingRemoteLiveWebContentViaPortletPG
`org.openqa.selenium.WebDriverException: unknown error: session deleted because of page crash`
* LocalFile.PGStaging#PublishWCViaRemoteStaging
`org.openqa.selenium.NoSuchSessionException: no such session`
* LocalFile.Staging#ViewInfoMessageAfterShutDownRemoteSite
`java.lang.Exception: An error occurred while executing waitForElementNotPresent`
`Caused by: java.util.concurrent.TimeoutException`

However, we can try to run them locally as well. My guess is that adding a new label is not likely to break existing tests.

**Comment by jorgediaz-lr** [comment]
@vendeltoreki we can also try to execute the test again

**Comment by vendeltoreki** [comment]
@jorgediaz-lr Yes, we can execute them, just the CI seemed to be a bit overloaded.

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by jorgediaz-lr** [comment]
Ok, thank you for launching it.

**Comment by jorgediaz-lr** [comment]
Hi @vendeltoreki 

The only staging test that has failed in both ci runs is:

- LocalFile.PGStaging#PublishWCViaRemoteStaging
`org.openqa.selenium.NoSuchSessionException: no such session`

I don't think it is related with my changes. 

Let me know if you think it is necessary to double check it.

Regards,
Jorge

**Comment by vendeltoreki** [comment]
Hi @jorgediaz-lr ,

You're right, the failure seems to be related to [LRCI-1048](https://issues.liferay.com/browse/LRCI-1048), so it's not related to this change.

Thanks,
Vendel

**Comment by jorgediaz-lr** [comment]
Thanks for finding that LRCI ticket.

Regards,
Jorge

**Comment by jorgediaz-lr** [comment]
Hi @vendeltoreki 

I have rebased this PR to latest master in order to solve some conflicts in following files:

- modules/apps/staging/staging-bar-web/src/main/resources/META-INF/resources/view_layout_revisions.jsp
- portal-kernel/bnd.bnd 

First one was caused by LPS-120962 changes, that were committed yesterday

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:staging

**Comment by jorgediaz-lr** [comment]
ci:test:staging

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Hi @vendeltoreki @moltam89

I have talked with @csierra about the change in TunnelUtil (https://github.com/vendeltoreki/liferay-portal/pull/124/commits/c1aa6db9da797157c19e902eeb01b0ce10e0bbb0), we have agreed to avoid changing it and solve the ClassNotFoundException in another way.

I will send you a new pull request with a different solution shortly.

Regards,
Jorge

**Pull request closed without merging**
