### PR TITLE
[TS] LPS-127658 | Last portlet configuration not restorable after deleting portlet.

### PR DESCRIPTION
**Pull request by bakayattila**
hi @vendeltoreki,

Could you review this?

https://issues.liferay.com/browse/LPS-127658

Thank you!

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
ci:test:staging

**Comment by gaborlovasdotcom** [comment]
ci:test:staging:nocompile

**Comment by vendeltoreki** [comment]
Hi @bakayattila ,

Thanks for the fix. As discussed, I'll investigate how we could improve it to handle Nested Portlets as well.

Regards,
Vendel

**Pull request closed without merging**
