### PR TITLE
[TS] LPS-128300

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-128300

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
Hi @ChrisKian ,

It seem like a similar fix had already been submitted for [LPS-128305](https://issues.liferay.com/browse/LPS-128305). However, your changes actually fix more scenarios. As soon as the other is merged to master, I'll forward your changes as well.

Regards,
Vendel

**Comment by vendeltoreki** [comment]
Closing this PR, forwarding on https://github.com/vendeltoreki/liferay-portal/pull/181 .

**Pull request closed without merging**
