### PR TITLE
Lps 122791

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-122791

Notes from @brianikim
>See link for description.
>
>The issue occurs because the current logic is incorrect in fetching the correct beginPos and endPos for string replacements in the URL. Therefore, the code never completes as of current.
>
>I tested the new implementation and confirmed it works as intended.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
Hi @brianikim ,

I've found some points where we could add some tests for the escaped HTML links: https://github.com/vendeltoreki/liferay-portal/pull/142

Running the tests before forwarding.

Thanks,
Vendel

**Comment by brianikim** [comment]
We can close this PR @SamZiemer , and keep track on https://github.com/vendeltoreki/liferay-portal/pull/142

**Pull request closed without merging**
