### PR TITLE
[TS] LPS-115024

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-115024

Previously sent to https://github.com/liferay-echo/liferay-portal/pull/989, but echo requested the PR be sent to staging.

Although Site Template pages are technically private pages and thus should not have any Guest permissions, it is possible to create public pages in a site when creating from the site template.  This results in the Guest view permission always being revoked when creating a site from a site template, even though the permission is enabled by default.

Using _isSiteTemplate() logic from [LayoutsAdminManagementToolbarDisplayContext._isSiteTemplate()](https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/display/context/LayoutsAdminManagementToolbarDisplayContext.java#L280).

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
Hi @ChrisKian ,

Thanks for the pull. I made some changes ( https://github.com/vendeltoreki/liferay-portal/pull/72/commits/867a9f50e14d34b3a79850f91ff6d4f5bf40c36f ) and started forwarding.

**Comment by ChrisKian** [comment]
Closing since https://github.com/vendeltoreki/liferay-portal/pull/72 has been created

**Pull request closed without merging**
