### PR TITLE
LPS-120487

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-120487

From @binhtran92:
> The old logic `layout.isTypeAssetDisplay()` was introduced by the ticket [LPS-106070](https://issues.liferay.com/browse/LPS-106070) to fixing the same issue as my ticket but in a different page template.
>
> I think it is not about the layout type, the root cause is that the portlet cannot find it's configuration on the `ManifestSummary` then it losing configuration
[ExportImportHelperImpl.java#L1218-L1232](https://github.com/hongvo2308/liferay-portal/blob/LPS-120487/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/lar/ExportImportHelperImpl.java#L1218-L1232)
>
> this PR also cover for ticket `LPS-106070`

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
Conversation regarding another pull request experiencing the same failure:

https://liferay.slack.com/archives/C19PWQ74J/p1600711838015000

**Comment by vendeltoreki** [comment]
Hi @holatuwol , @binhtran92 ,

The changes look ok from staging perspective. I will forward it once the CI issues are fixed.

Thanks,
Vendel

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
