### PR TITLE
LPS-94690 Async status monitoring for remote staging

### PR DESCRIPTION
**Pull request by knchau**
https://issues.liferay.com/browse/LPS-94690

As discussed, implemented a fix by using properties and manual configuration. 

Add a boolean property (false by default), and when it's true, users can define the Live site URL manually in staging configuration. This way, nothing will change for existing users. Only those will set this property, who have problem with a slow staging site.

### CODE REVIEW

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Hi @knchau ,

Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/83855 .

Thanks,
Vendel

**Pull request closed without merging**
