### PR TITLE
LPS-139101

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-139101

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
