### PR TITLE
[TS] LPS-142111 Add callback event only when the event ID list is not null and not empty

### PR DESCRIPTION
**Pull request by vendeltoreki**
Invert the condition of `isNotEmpty`: https://github.com/liferay/liferay-portal/commit/cd9fcdc49cc100209d89bdfd737435e4721a1263

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:reevaluate:1267401_792

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:forward

**Pull request closed without merging**
