### PR TITLE
LPS-123156 As a Content Publisher, I want to have clear distinction among Staging and Publications UI labels and phrases

### PR DESCRIPTION
**Pull request by moltam89**

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test:sf

**Comment by moltam89** [comment]
si:test:relevant

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
Add additional test-fix for **switch-to-advanced-publication** and quarantine unrelated failed tests.
https://github.com/moltam89/liferay-portal/pull/561

**Comment by moltam89** [comment]
Rebased and resent here:
https://github.com/JoyceWang08211/liferay-portal/pull/189

Thanks!

**Pull request closed without merging**
