### PR TITLE
LPS-134316

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-134316

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
cc: @liferay-echo team, since the change affects how DL references are replaced in contents. From staging point of view, it looks OK to me.

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
