### PR TITLE
LPS-123482 Check the virtual layout case in order to see whether the staged site has private pages or not

### PR DESCRIPTION
**Pull request by dacousalr**
Hi @vendeltoreki,

This solution tries to cover the case where the remote URL is obtained from the Staging site when navigating through administrative pages.

An alternative solution could be to request the public LayoutSet when the group has at least one public page instead of requesting the public LayoutSet when the group has no private pages.

Could you please review it?

Please, also let me know if you need further clarifications on this or you think that the Echo team should (also) review it.

Thanks in advance,
Daniel

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Hi @vendeltoreki,

Just a question while the review is not done yet: would it be safe to deliver this as SDH?

Thanks in advance

**Comment by vendeltoreki** [comment]
Hi @dacousalr ,

I've just started the review process. The changes look OK to me. If it doesn't break anything, I think it can be released as an SDH.

Regards,
Vendel

**Comment by dacousalr** [comment]
Thanks, @vendeltoreki!

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
The staging test failures don't seem to be unique, as mostly the same tests are failing in acceptance run: https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1343895616
`LocalFile.Staging#StagingRemoteDMDocumentType` is the only one that seems to be failing, but it did not fail in the previous staging test run on this same PR.

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
