### PR TITLE
LPS-136250 restoring count when exporting reference

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
ci:test:staging

**Comment by moltam89** [comment]
Hi @linolaoj ,

If I understand it correctly, the issue is the following:

On the export screen, only the entries which will be definitely exported  show up. References are not included, as those are only available after the export really happened.

On the import screen however, we already know how many entities were actually exported, and the final numbers are displayed.

The current solution in this PR is to ignore the references, and even though there were more entries exported via the references, we only display the numbers which match the export screen.

I'm not sure if this is the right direction, I think it's better to let users know the final numbers before the import.
In general, I think the current behaviour  in master is the expected to one.
(During testing, I saw that the import screen shows 3 for Folders, which is probably a bug, as only 1 folder was exported/imported).

Do we know what is the customer's expectation?

Best,
Tamas

**Comment by linolaoj** [comment]
Hi @moltam89 , your understanding is correct. The customer expects both numbers to be the same on the export and import screen. This pr is to ignore the referenced models that were exported. If the master behavior is expected, I can explain on LPP-42196 that the current behavior is the correct one.
Please let me know if more details are needed.
Thanks!

**Comment by moltam89** [comment]
Hi @linolaoj ,

Okay, let's try to explain the behaviour to the customer.
I think it's normal that the referenced entities show up on the import screen.

Thanks,
Tamas

**Pull request closed without merging**
