### PR TITLE
[TS] LPS-110838  Add "replicate individual deletions" and "publish permissions" default configurations to system settings

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-110838

This is a perceived bug by some customers. They need "Replicate Individual Deletions" and "Publish Permissions" staging options to be enabled by default:

- Their use case is to always publish deletions and permission changes from staging to live.
- So their user has to always manually check both checkboxes before publishing
- Their concern is in case their user forgets to check them one time, it is very difficult to notice the error and fix it.

My proposal is to make default checkbox values configurable from System Settings.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Hi @vendeltoreki 

Do you have any update about this PR?

Thank you,
Jorge Díaz

**Comment by vendeltoreki** [comment]
Hi @jorgediaz-lr ,

I'm running some CI tests to see if it doesn't break any test case: https://github.com/vendeltoreki/liferay-portal/pull/46

I will run some manual tests as well and forward it right after that.

Regards,
Vendel

**Comment by jorgediaz-lr** [comment]
Thank you for the information @vendeltoreki !!

I will wait until CI tests are executed and you run the manual tests.

Regards,
Jorge

**Comment by vendeltoreki** [comment]
Forwarded to: https://github.com/brianchandotcom/liferay-portal/pull/86946

**Comment by jorgediaz-lr** [comment]
Thank you, @vendeltoreki

**Pull request closed without merging**
