### PR TITLE
LPS-135975, LPS-136196 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LPS-135975
https://issues.liferay.com/browse/LPS-136196

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
cc @gaborlovasdotcom

**Comment by mbowerman** [comment]
Hi @vendeltoreki,

We had this message on our Slack channel:

https://liferay.slack.com/archives/CL8DNJYB0/p1627331571173800

> Hi Support and technical_support, please continue to send bug fixes to master. These changes are still allowed and should not be hindered by the 7.4 release process.

Is it possible to forward this to Brian Chan, since it is a bug fix?

**Comment by moltam89** [comment]
Hi @mbowerman ,

Vendel is on vacation, but he left a note that if the tests are passing we can forward this.

Cheers,
Tamas

**Comment by moltam89** [comment]
ci:forward

**Pull request closed without merging**
