### PR TITLE
LPS-116620 Set the property for sql server

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@balazssk and @vendeltoreki I haven't tested this one.  Can one of you confirm this resolves the issue?

Thanks!

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
Hi @Preston-Crary ,

Thanks for the quick fix. I will run some tests to see if it works. As far as I know, the Oracle fix splits the values into multiple `IN (..) ` statements, concatenated by `OR` in the same query:
```
IN (0, 1, 2, ....., 999) OR
IN (1000, ..... 1999) OR
IN (2000, ..... 2999) OR
```

I'm not completely sure, but the 2100 limitation of the SQL Server is for the whole query. I will check that.

**Comment by Preston-Crary** [comment]
Hi @vendeltoreki,

if this doesn't work let's go with https://github.com/vendeltoreki/liferay-portal/pull/81.  It's much simpler but less in line with what Brian was asking for.

**Comment by vendeltoreki** [comment]
Hi @Preston-Crary ,

I've tested it, but it did not work. The `database.in.max.parameters[sqlserver]=2000` parameter only splits the `IN (..)` condition and SQL Server expects the total number of parameters per query to be less than 2100. In fact, CS also [tested it](https://issues.liferay.com/browse/LPP-38096?focusedCommentId=2192535&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2192535) before.

I'm also thinking about a framework-level solution, but that would be really complex and it won't work for all cases (e.g. when the `IN` is not used as a simple filter or there are multiple `IN` conditions). My guess is that the best solution is to simply avoid such cases.

So I'm going with https://github.com/vendeltoreki/liferay-portal/pull/81 . I don't think it will have huge performance impact, since the deletions are already done one-by-one.

As I see, we are already using some kind of batching, for example in [ResourcePermissionLocalServiceImpl](https://github.com/liferay/liferay-portal/blob/1c2dc2ae9678954fdf5541b29aeae5afa6e77c70/portal-impl/src/com/liferay/portal/service/impl/ResourcePermissionLocalServiceImpl.java#L1795), but that's not DB specific.

Thanks,
Vendel

**Comment by Preston-Crary** [comment]
Sounds good.

**Pull request closed without merging**
