### PR TITLE
LPS-113739 Semantic Versioning.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
Hi @marianoalvarosaiz ,

I think all CI errors are irrelevant. However, I will run them once again, to see whether they are fixed. Otherwise, your changes look good.

Thanks,
Vendel

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
