### PR TITLE
LPS-108283 Make sure that service context is always in place when copying a layout

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by vendeltoreki** [comment]
Closing: merged in https://github.com/brianchandotcom/liferay-portal/pull/85164

**Pull request closed without merging**
