### PR TITLE
LPS-119922 StagingBarPortlet - Mark actual Live page version in Local Staging

### PR DESCRIPTION
**Pull request by moltam89**

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by moltam89** [comment]
ci:test:staging

**Comment by brianikim** [comment]
Hello @vendeltoreki ,

Any updates on this PR?

Sincerely,
Brian

**Comment by vendeltoreki** [comment]
Hi @brianikim , @moltam89 ,

I plan to do this review today.

Regards,
Vendel

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
