### PR TITLE
[TS] LPS-121342

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Hi @vendeltoreki @moltam89

Same changes than https://github.com/vendeltoreki/liferay-portal/pull/126 PR, but I have added some tests in StagingImplTest class, see commits: [`fc88d8c` (#127)](https://github.com/vendeltoreki/liferay-portal/pull/127/commits/fc88d8cb528dad3cb596a860a85baf80e86bc677) and [`d9920d6` (#127)](https://github.com/vendeltoreki/liferay-portal/pull/127/commits/d9920d62069869213a53679aff38939aebf9c3bf)

I have added four tests:

- Two that tests just the remote staging publication: `testRemoteStaging()` and `testRemoteStagingWithLayoutVersioning()`
- Another two tests that test the new methods: `testGetRemoteLayout()` and `testHasRemoteLayout()`

Let me know if you have any question

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
Thanks, @jorgediaz-lr . I've forwarded it to https://github.com/brianchandotcom/liferay-portal/pull/94756 .

**Comment by jorgediaz-lr** [comment]
Thank you, @vendeltoreki

**Pull request closed without merging**
