### PR TITLE
LPS-107936 Widget Templates are not visible with Staging enabled

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-107936](https://issues.liferay.com/browse/LPS-107936)

Hi Vendel,

Please review my changes. From the history of the surrounding code I think this is the correct fix, because similar issues were also fixed by adding the corresponding action ids into the same place.

If you have any concerns, feel free to find me with them.

Thank you,
Pisti

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Hi @istvansajtos ,

I've checked your commit https://github.com/vendeltoreki/liferay-portal/pull/27/commits/d39af89f6396e6ccbfadcd3d10131075c007537c . However, I'm not yet 100% convinced that this is the right solution. This part of the code contains the permissions that should not be taken away in Live, when that specific portlet is staged (otherwise, everything in the Live site would be locked). This change somehow also affects the permission in the Staging site, which doesn't seem right. I will investigate it next week.

Regards,
Vendel

**Comment by vendeltoreki** [comment]
Hi @istvansajtos,

I've forwarded a modified version: https://github.com/brianchandotcom/liferay-portal/pull/84915

Thanks,
Vendel

**Pull request closed without merging**
