### PR TITLE
LPS-113197

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hello @vendeltoreki,

Please let me know if you have any questions about these changes or if you have a different idea as to how to resolve this issue.

Thank you.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Hi @jonathanmccann ,

These changes seem ok. It's weird that nobody noticed these errors so far. Most of the cases are reproducible even in 7.0.

Thanks,
Vendel

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
