### PR TITLE
[TS] LPS-122791 Convert staging URLs in HTML fragments

### PR DESCRIPTION
**Pull request by vendeltoreki**

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by brianikim** [comment]
Hello @vendeltoreki ,

Any updates on the PR?

Sincerely,
Brian

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
